# Generated by Django 4.0.3 on 2023-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_audio', models.FileField(upload_to='original/')),
                ('original_text', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('processed_text', models.TextField()),
                ('processed_audio', models.FileField(upload_to='processed/')),
            ],
        ),
    ]
