# Generated by Django 4.0.3 on 2023-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='original_audio',
            field=models.FileField(blank=True, null=True, upload_to='original/'),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
