# Generated by Django 4.0.3 on 2023-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioProcessing', '0002_alter_audiodata_original_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='original_text',
            field=models.TextField(blank=True),
        ),
    ]
