# Generated by Django 4.0.3 on 2023-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioProcessing', '0003_alter_audiodata_original_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
