# Generated by Django 4.0.3 on 2023-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioProcessing', '0004_alter_audiodata_original_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='original_text',
            field=models.TextField(blank=True),
        ),
    ]
