# Generated by Django 4.0.3 on 2023-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioProcessing', '0005_alter_audiodata_original_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='processed_text',
            field=models.TextField(blank=True),
        ),
    ]
